# Generated by Django 5.1.4 on 2026-05-29 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_category_budget_alter_transaction_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CSV", "Eksport CSV"),
                            ("PDF", "Raport PDF"),
                            ("AI", "Analiza AI"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Oczekuje"),
                            ("PROCESSING", "W trakcie"),
                            ("DONE", "Gotowe"),
                            ("FAILED", "Blad"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("file", models.FileField(blank=True, null=True, upload_to="reports/")),
                ("result", models.TextField(blank=True, default="")),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
